cours4/td_backend/src/Entity/Film.php
<?php

namespace App\Entity;

use App\Repository\FilmRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FilmRepository::class)]
class Film
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\OneToOne(inversedBy: 'film_id', cascade: ['persist', 'remove'])]
    private ?Realisateur $realisateur_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getRealisateurId(): ?Realisateur
    {
        return $this->realisateur_id;
    }

    public function setRealisateurId(?Realisateur $realisateur_id): static
    {
        $this->realisateur_id = $realisateur_id;

        return $this;
    }
}

cours4/td_backend/src/Entity/Realisateur.php
<?php

namespace App\Entity;

use App\Repository\RealisateurRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RealisateurRepository::class)]
class Realisateur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\OneToOne(mappedBy: 'realisateur_id', cascade: ['persist', 'remove'])]
    private ?Film $film_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getFilmId(): ?Film
    {
        return $this->film_id;
    }

    public function setFilmId(?Film $film_id): static
    {
        // unset the owning side of the relation if necessary
        if ($film_id === null && $this->film_id !== null) {
            $this->film_id->setRealisateurId(null);
        }

        // set the owning side of the relation if necessary
        if ($film_id !== null && $film_id->getRealisateurId() !== $this) {
            $film_id->setRealisateurId($this);
        }

        $this->film_id = $film_id;

        return $this;
    }
}

cours4/td_backend/src/Controller/FilmController.php
<?php

namespace App\Controller;

use App\Repository\FilmRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class FilmController extends AbstractController
{
    #[Route('/film', name: 'app_film')]
    public function index(FilmRepository $filmRepository): Response
    {
        $films = $filmRepository->findAll();

        return $this->render('film/index.html.twig', [
            'controller_name' => 'FilmController',
            'films' => $films,
        ]);
    }
}

cours4/td_backend/src/Controller/RealisateurController.php
<?php

namespace App\Controller;

use App\Repository\RealisateurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class RealisateurController extends AbstractController
{
    #[Route('/realisateur', name: 'app_realisateur')]
    public function index(RealisateurRepository $realisateurRepository): Response
    {
        $realisateurs = $realisateurRepository->findAll();

        return $this->render('realisateur/index.html.twig', [
            'controller_name' => 'RealisateurController',
            'realisateurs' => $realisateurs,
        ]);
    }
}

cours4/td_backend/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
{% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

cours4/td_backend/templates/film/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FilmController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Liste des films</h1>

    {% if films is empty %}
        <p>Aucun film en base.</p>
    {% else %}
        <ul>
            {% for film in films %}
                <li>
                    <strong>{{ film.titre }}</strong><br>

                    Réalisateur :
                    {{ film.realisateurId.prenom }}
                    {{ film.realisateurId.nom }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% endblock %}

cours4/td_backend/templates/realisateur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello RealisateurController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<div class="example-wrapper">
    <h1>Liste des réalisateurs</h1>

    {% if realisateurs is empty %}
        <p>Aucun réalisateur en base.</p>
    {% else %}
        <ul>
            {% for realisateur in realisateurs %}
                <li>
                    <strong>{{ realisateur.prenom }} {{ realisateur.nom }}</strong><br>
                    Film :
                    {% if realisateur.filmId %}
                        {{ realisateur.filmId.titre }}
                    {% else %}
                        <em>Aucun film associé</em>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% endblock %}